version: '2'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    hostname: nginx
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./files:/etc/nginx/conf.d
    networks:
      - gitbucket_default
    ports:
      - "${NGINX_EXTERNAL_PORT}:80"

networks:
  gitbucket_default:
    external: true
